### ISSUE TITLE
Exclude flag including excluded filetypes

### ISSUE THREAD

**Issue by adamnmcc** [tbenz9/siasync#1]
Hi, I'm trying to use Siasync to have an offsite decentralised back up of my Nextcloud installation. 

using the command below, i am having an issue whereby the Sync process is not ignoring the log and DB files which are updated on an almost by the second basis. 

`Siasync-linux-amd64 -password xxxxxx -exclude db,log -subfolder siasync -debug /media/4tb/nextcloud/data/`

debug output
`Found extension in include flag
2019/06/14 11:09:02 change in /media/4tb/nextcloud/data/owncloud.db detected, reuploading..
Extension not found in include flag
Extension not found in include flag`

**Comment by tbenz9** [comment]
Thank you for reporting this.  I tracked it down and fixed it in beta 2 which was just released.  Feel free to grab the newest Binaries and try again!

**Comment by tbenz9** [comment]
https://github.com/tbenz9/siasync/commit/94adc701a8f32c0fd4ac2aa09faf94a8313c240a is the commit that fixes this issue.
